#!/bin/sh

set -eu

script_dir=$(CDPATH= cd -P "$(dirname "$0")/.." && pwd)
relay=$script_dir/scripts/dev-relay
test_root=$(mktemp -d "${TMPDIR:-/tmp}/rde-relay-embedded-test.XXXXXX")
trap 'rm -rf "$test_root"' EXIT HUP INT TERM

extract_script() {
  assignment=$1
  destination=$2
  awk -v assignment="$assignment" '
    BEGIN { quote = sprintf("%c", 39); capturing = 0; found = 0 }
    !capturing && index($0, assignment) == 1 {
      capturing = 1
      line = $0
      sub("^.*=" quote, "", line)
      print line
      next
    }
    capturing {
      if (substr($0, length($0), 1) == quote) {
        line = $0
        sub(quote "$", "", line)
        print line
        found = 1
        exit
      }
      print
    }
    END {
      if (!found) exit 1
    }
  ' "$relay" > "$destination"
  sh -n "$destination"
}

project_script=$test_root/project-remote.sh
ssh_script=$test_root/vm-ssh.sh
trust_script=$test_root/vm-trust.sh
wrapper_script=$test_root/vm-wrapper.sh
extract_script '  project_remote_script=' "$project_script"
extract_script '  remote_install_config=' "$ssh_script"
extract_script '  remote_install_known_host=' "$trust_script"
extract_script '  remote_install_wrapper=' "$wrapper_script"

project=$test_root/project
mkdir -p "$project"
cat > "$project/.dev-exec.env" <<'EOF'
# Generated by remote-dev-execution dev-relay setup
DEV_EXEC_HOST='old-host'
DEV_EXEC_DIR='/old/path'
DEV_EXEC_MUTAGEN_SESSION='keep-session'
DEV_EXEC_MUTAGEN_BIN='/old/bin/mutagen'
DEV_EXEC_MUTAGEN_HOST='keep-control'
EOF

printf '%s\n' \
  "$project" \
  0 \
  '# Generated by remote-dev-execution dev-relay setup' \
  "DEV_EXEC_HOST='new-host'" \
  "DEV_EXEC_DIR='/new/path'" |
  sh "$project_script" >/dev/null
grep -Fqx "DEV_EXEC_MUTAGEN_SESSION='keep-session'" "$project/.dev-exec.env"
grep -Fqx "DEV_EXEC_MUTAGEN_BIN='/old/bin/mutagen'" "$project/.dev-exec.env"
grep -Fqx "DEV_EXEC_MUTAGEN_HOST='keep-control'" "$project/.dev-exec.env"

printf '%s\n' \
  "$project" \
  1 \
  '# Generated by remote-dev-execution dev-relay setup' \
  "DEV_EXEC_HOST='clear-host'" \
  "DEV_EXEC_DIR='/clear-path'" |
  sh "$project_script" >/dev/null
! grep -q 'DEV_EXEC_MUTAGEN_SESSION' "$project/.dev-exec.env"
! grep -q 'DEV_EXEC_MUTAGEN_BIN' "$project/.dev-exec.env"
! grep -q 'DEV_EXEC_MUTAGEN_HOST' "$project/.dev-exec.env"

printf '%s\n' \
  "$project" \
  0 \
  '# Generated by remote-dev-execution dev-relay setup' \
  "DEV_EXEC_HOST='remote-host'" \
  "DEV_EXEC_DIR='/remote/path'" \
  "DEV_EXEC_MUTAGEN_SESSION='new-session'" \
  "DEV_EXEC_MUTAGEN_HOST='new-control'" \
  "DEV_EXEC_MUTAGEN_BIN='/opt/mutagen'" |
  sh "$project_script" >/dev/null
grep -Fqx "DEV_EXEC_MUTAGEN_SESSION='new-session'" "$project/.dev-exec.env"
grep -Fqx "DEV_EXEC_MUTAGEN_HOST='new-control'" "$project/.dev-exec.env"
grep -Fqx "DEV_EXEC_MUTAGEN_BIN='/opt/mutagen'" "$project/.dev-exec.env"

printf '%s\n' 'test-relay-embedded: all checks passed'
